#!/bin/bash

month=$1

if [ -z $month ]
then
    echo "No month number given"
    exit
fi

case $month in
"1")
    echo "January"
    ;;
"2")
    echo "Febuary"
    ;;
"3")
    echo "March"
    ;;
"4")
    echo "Arpil"
    ;;
"5")
    echo "May"
    ;;
"6")
    echo "June"
    ;;
"7")
    echo "July"
    ;;
"8")
    echo "August"
    ;;
"9")
    echo "September"
    ;;
"10")
    echo "October"
    ;;
"11")
    echo "November"
    ;;
"12")
    echo "December"
    ;;
*)
    echo "Invalid month number given"
    ;;
esac